import React from "react";

export const metadata = {
  title: "Create an Account - Upwork",
  description: "Generated by Wesam Abutaima",
};

const SignupLayout = ({ children }) => {
  return <>{children}</>;
};

export default SignupLayout;
