"use client";
import React from "react";
import AuthFooter from "@/components/AuthFooter";

export const metadata = {
  title: "Upwork Login - Login in to your upwork account",
  description: "Generated by Wesam Abutaima",
};

const SignupLayout = ({ children }) => {
  return (
    <>
      {children}
      <AuthFooter />
    </>
  );
};

export default SignupLayout;
